##Multiple Linear Regression

Business -> Build a model that can predict accurate profits on basis of RND and MKT

Step1: Data Ingestion/Data Gathering

In [6]:
import pandas as pd
path=r"https://raw.githubusercontent.com/sindhura-nk/Datasets/refs/heads/main/50_Startups.csv"
df = pd.read_csv(path)
df.head()

URLError: <urlopen error [Errno 11001] getaddrinfo failed>

Step2: Perform basic data quality checks

In [3]:
df.shape

(50, 5)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   RND     50 non-null     float64
 1   ADMIN   50 non-null     float64
 2   MKT     50 non-null     float64
 3   STATE   50 non-null     str
 4   PROFIT  50 non-null     float64
dtypes: float64(4), str(1)
memory usage: 2.1 KB

In [5]:
df.isna().sum()

RND       0
ADMIN     0
MKT       0
STATE     0
PROFIT    0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

Step3: Separate the X and Y features

    X: RND , MKT
    Y: PROFIT

In [7]:
X=df[['RND','MKT']]
Y=df[['PROFIT']]
display(X)
display(Y)

          RND        MKT
0   165349.20  471784.10
1   162597.70  443898.53
2   153441.51  407934.54
3   144372.41  383199.62
4   142107.34  366168.42
5   131876.90  362861.36
6   134615.46  127716.82
7   130298.13  323876.68
8   120542.52  311613.29
9   123334.88  304981.62
10  101913.08  229160.95
11  100671.96  249744.55
12   93863.75  249839.44
13   91992.39  252664.93
14  119943.24  256512.92
15  114523.61  261776.23
16   78013.11  264346.06
17   94657.16  282574.31
18   91749.16  294919.57
19   86419.70       0.00
20   76253.86  298664.47
21   78389.47  299737.29
22   73994.56  303319.26
23   67532.53  304768.73
24   77044.01  140574.81
25   64664.71  137962.62
26   75328.87  134050.07
27   72107.60  353183.81
28   66051.52  118148.20
29   65605.48  107138.38
30   61994.48   91131.24
31   61136.38   88218.23
32   63408.86   46085.25
33   55493.95  214634.81
34   46426.07  210797.67
35   46014.02  205517.64
36   28663.76  201126.82
37   44069.95  197029.42
38   20229.59  185265.10
39   38558.51  174999.30
40   28754.33  172795.67
41   27892.92  164470.71
42   23640.93  148001.11
43   15505.73   35534.17
44   22177.74   28334.72
45    1000.23    1903.93
46    1315.46  297114.46
47       0.00       0.00
48     542.05       0.00
49       0.00   45173.06

       PROFIT
0   192261.83
1   191792.06
2   191050.39
3   182901.99
4   166187.94
5   156991.12
6   156122.51
7   155752.60
8   152211.77
9   149759.96
10  146121.95
11  144259.40
12  141585.52
13  134307.35
14  132602.65
15  129917.04
16  126992.93
17  125370.37
18  124266.90
19  122776.86
20  118474.03
21  111313.02
22  110352.25
23  108733.99
24  108552.04
25  107404.34
26  105733.54
27  105008.31
28  103282.38
29  101004.64
30   99937.59
31   97483.56
32   97427.84
33   96778.92
34   96712.80
35   96479.51
36   90708.19
37   89949.14
38   81229.06
39   81005.76
40   78239.91
41   77798.83
42   71498.49
43   69758.98
44   65200.33
45   64926.08
46   49490.75
47   42559.73
48   35673.41
49   14681.40

Step4: Feature Engineering:-> Data Cleaning

In [9]:
from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer

num_pipe = (SimpleImputer(strategy='median')).set_output(transform='pandas')
num_pipe

SimpleImputer(strategy='median')


Pipeline(steps=[('simpleimputer', SimpleImputer(strategy='median'))])

    In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook.
    On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.

Step5: Separate our data into training and testing

dataset size is small: 80% and above training : 20% and below testing

In [11]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest= train_test_split(X,Y ,train_size=0.8,random_state=21)

In [12]:
print(xtrain.shape,xtest.shape)

(40, 2) (10, 2)

In [4]:
print(ytrain.shape,ytest.shape)

NameError: name 'ytrain' is not defined

Apply the pipeline on training and testing data

In [14]:
num_pipe.fit(xtrain)

SimpleImputer(strategy='median')


    Pipeline(steps=[('simpleimputer', SimpleImputer(strategy='median'))])
    In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook.
    On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.

In [3]:
xtrain_pre=num_pipe.transform(xtrain)
xtest_pre=num_pipe.transform(xtest)

NameError: name 'num_pipe' is not defined

Step5: Model Building

In [17]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(xtrain_pre,ytrain)

LinearRegression()

    LinearRegression()
    In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook.
    On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.

Check for coefficients(slopes) and yintercept

In [2]:
X.shape[1]

NameError: name 'X' is not defined

In [19]:
X.columns

Index(['RND', 'MKT'], dtype='str')

In [20]:
model.coef_

array([[0.80684176, 0.02873112]])

In [21]:
model.intercept_

array([46739.04153534])

PROFIT_PREDICTED = 46739.04 + (0.806)RND + (0.028)MKT

In [22]:
ypred_test=model.predict(xtest_pre)
ypred_test[:5]

array([[161174.35424088],
       [ 65447.05658197],
       [ 60270.64856584],
       [102877.05072467],
       [150884.1602036 ]])

In [23]:
ytest.head()

       PROFIT
7   155752.60
44   65200.33
43   69758.98
25  107404.34
14  132602.65

Step 6: Model Evaluation : Performance Metrics

In [1]:
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

mse = mean_squared_error(ytest,ypred_test)
mae = mean_absolute_error(ytest,ypred_test)
rmse = mse**0.5
r2 = r2_score(ytest,ypred_test)

print(f"Testing scores")
print(f"MSE:{mse}")
print(f"MAE:{mae}")
print(f"RMSE:{rmse}")
print(f"R2 score-Coefficient of Determination:{r2*100:.2f}")

NameError: name 'ytest' is not defined

R2 Score for the model is above 80%. We can consider this model for final deployments.

In [7]:
import joblib
joblib.dump(model,"MLR_ProfitPrediction.joblib")
joblib.dump(num_pipe,"cleaning_pipeline.joblib")

NameError: name 'model' is not defined

In [8]:
model_loaded= joblib.load("MLR_ProfitPrediction.joblib")
pipeline_loaded = joblib.load("cleaning_pipeline.joblib")

FileNotFoundError: [Errno 2] No such file or directory: 'MLR_ProfitPrediction.joblib'

    In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook.
    On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.

In [9]:
pipeline_loaded

NameError: name 'pipeline_loaded' is not defined

    In a Jupyter environment, please rerun this cell to show the HTML representation or trust the notebook.
    On GitHub, the HTML representation is unable to render, please try loading this page with nbviewer.org.